services:
  model:
    build: ./model-app
    image: number-inference-model:latest
    volumes:
      - ./model-app:/app
      - model_volume:/model
      - data_volume:/data
      - logs_volume:/logs
      
  serve:
    build: ./serve-app
    image: number-inference-serve:latest
    volumes:
      - ./serve-app:/app 
      - model_volume:/model
    ports:
      - "5000:5000"  

  web:
    build: ./web-app
    image: number-inference-web:latest
    volumes:
      - ./web-app:/app
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=development   
#    depends_on: 
#      - serve

  tensorboard:
      image: tensorflow/tensorflow:latest
      volumes:
        - logs_volume:/app/tensorboard_logs  
      ports:
        - "6006:6006"
      command: tensorboard --logdir=/app/tensorboard_logs --host 0.0.0.0

volumes:
  model_volume:
  data_volume:
  logs_volume: 